"""Task 4 driver (accuracy-offline-gate plan): pre-refactor baseline freeze.

Runs the deduplicated Gate B corpus (spec Sec.6/Sec.7) through the CURRENT, unmodified
``heuristic_choose_for_request`` with ``SHOWDOWN_ACCURACY_MODE`` explicitly off, and freezes
the result as ``data/eval/accuracy-gate/pre-refactor-baseline.jsonl``.

**This artifact is a hard checkpoint: once committed, never regenerate it.** It must be
captured from the unmodified evaluate_line/heuristic_choose_for_request, before Task 5's
LineEvaluation refactor lands -- it is the ground truth every later regression check diffs
against.

Usage (from the showdown_bot/ directory of this worktree):

    PYTHONPATH="$(pwd)/src" python scripts/run_accuracy_baseline_freeze.py

(PYTHONPATH must point at THIS worktree's src/ -- the machine has an editable pip install of
showdown-bot pointing at the main repo checkout, not this worktree; without the override,
imports silently resolve to the wrong package.)
"""

from __future__ import annotations

import glob
import hashlib
import json
import os
import subprocess
import sys
import time
from dataclasses import asdict
from pathlib import Path

# Real calc backend, persistent Node process -- avoids a fresh spawn per decision across the
# ~600-800 real MOVE decisions this script processes (matches scratchpad/bench_accuracy_latency.py's
# "production/Kaggle mode" convention). SHOWDOWN_CALC_BACKEND is NON_BEHAVIORAL (eval/config_env.py)
# -- transport only, never affects config_hash or which move is chosen.
os.environ.setdefault("SHOWDOWN_CALC_BACKEND", "persistent")

SCRIPT_DIR = Path(__file__).resolve().parent
SHOWDOWN_BOT_ROOT = SCRIPT_DIR.parent
REPO_ROOT = SHOWDOWN_BOT_ROOT.parent
sys.path.insert(0, str(SHOWDOWN_BOT_ROOT / "src"))  # shadow the editable install (main-repo gotcha)

DATA_EVAL = REPO_ROOT / "data" / "eval"
OUT_DIR = DATA_EVAL / "accuracy-gate"
BASELINE_OUT = OUT_DIR / "pre-refactor-baseline.jsonl"
DEDUP_REPORT_OUT = OUT_DIR / "dedup-report.json"

FORMAT_ID = "gen9vgc2025regi"
DRY_RUN_N = 50
EXPECTED_FINAL_G = 85  # plan's directly-verified real-corpus number (see plan's provenance-facts)


def _rel(path: Path) -> str:
    """Repo-relative, forward-slash path -- for a committed artifact that must not embed one
    machine's absolute path layout."""
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def _file_content_hash(path) -> str | None:
    """sha1[:16] of a file's bytes (mirrors cli.py's own config-hash provenance helper --
    kept as a local copy since cli.py's is a private, unexported function)."""
    try:
        return hashlib.sha1(Path(path).read_bytes()).hexdigest()[:16]
    except Exception:  # noqa: BLE001 - provenance is best-effort; missing file -> None
        return None


def main() -> None:
    from showdown_bot.battle.decision import heuristic_choose_for_request
    from showdown_bot.battle.decision_trace import DecisionTrace
    from showdown_bot.battle.opponent import SpeciesDex
    from showdown_bot.battle.oracle import DamageOracle
    from showdown_bot.engine.belief.hypotheses import load_spread_book
    from showdown_bot.engine.calc.client import CalcClient
    from showdown_bot.engine.format_config import load_format_config
    from showdown_bot.engine.moves import movedata_path
    from showdown_bot.engine.speed import SpeedOracle
    from showdown_bot.eval.accuracy_baseline import freeze_baseline
    from showdown_bot.eval.config_env import behavior_env, build_config_manifest, config_provenance_for_format
    from showdown_bot.eval.result_jsonl import make_config_hash
    from showdown_bot.eval.room_raw_replay import (
        RequestKind,
        deduplicate_battle_logs,
        extract_decisions_from_log,
    )

    print(f"showdown_bot resolved from: {SHOWDOWN_BOT_ROOT}")

    # --- Guard: this baseline is a hard checkpoint (spec Sec.7) -- once committed, it must
    # NEVER be regenerated by re-running this script. Re-running would silently clobber the
    # frozen ground truth that every later refactor-regression diff (Task 10) checks against,
    # and re-freezing after the codebase has moved on would defeat the whole point of a
    # pre-refactor snapshot. Deleting/regenerating this file is a decision that requires
    # explicit human judgment (and a fresh, deliberate justification), not an accidental re-run.
    if BASELINE_OUT.exists():
        raise SystemExit(
            f"REFUSING TO RUN: {BASELINE_OUT} already exists.\n"
            f"This file is a hard checkpoint (spec Sec.7): it was captured from the "
            f"pre-refactor heuristic_choose_for_request and must never be regenerated once "
            f"committed -- every later refactor-regression check diffs against it as ground "
            f"truth. If you believe this file genuinely needs to be regenerated, that is a "
            f"decision requiring explicit human judgment, not a re-run of this script: delete "
            f"the file yourself (with full awareness of what you are invalidating) before "
            f"re-running."
        )

    # --- Step 1: glob every .log.gz under the 4 canonical corpus directories ---
    glob_dirs = [
        DATA_EVAL / "t4" / "rerun" / "room_raw",
        DATA_EVAL / "t4" / "room_raw_divergent",
        DATA_EVAL / "t6" / "room_raw",
        DATA_EVAL / "kaggle-validation" / "room_raw",
    ]
    log_files: list[Path] = []
    for d in glob_dirs:
        log_files += [Path(p) for p in glob.glob(str(d / "**" / "*.log.gz"), recursive=True)]
    log_files = sorted(set(log_files), key=str)
    print(f"found {len(log_files)} .log.gz files under the 4 canonical corpus directories")

    # --- Step 2: global battle-level dedup (Task 2's deduplicate_battle_logs) ---
    manifest_files = [
        DATA_EVAL / "t4" / "rerun" / "t4rerun-run1.jsonl",
        DATA_EVAL / "t4" / "rerun" / "t4rerun-run2.jsonl",
        DATA_EVAL / "t4" / "rerun" / "t4rerun-prefix.jsonl",
        DATA_EVAL / "t6" / "t6-run1.jsonl",
        DATA_EVAL / "t6" / "t6-run2.jsonl",
        DATA_EVAL / "kaggle-validation" / "results.jsonl",
    ]
    report = deduplicate_battle_logs(
        log_files=log_files, manifest_files=manifest_files,
        keep_priority=["run1", "run2", "prefix", "kaggle-validation"],
    )
    print(f"dedup: files_found={report.files_found} kept={len(report.kept)} "
          f"excluded={len(report.excluded)} final_g={report.final_g}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    kept_sorted = sorted(report.kept, key=str)
    dedup_report_payload = {
        "files_found": report.files_found,
        "final_g": report.final_g,
        "kept": [_rel(p) for p in kept_sorted],
        "kept_identities": {
            _rel(p): asdict(identity)
            for p, identity in sorted(report.kept_identities.items(), key=lambda kv: str(kv[0]))
        },
        "excluded": [
            {
                "source_file": _rel(e.source_file),
                "reason": e.reason,
                "duplicate_of": _rel(e.duplicate_of) if e.duplicate_of is not None else None,
            }
            for e in sorted(report.excluded, key=lambda e: str(e.source_file))
        ],
    }

    if report.final_g != EXPECTED_FINAL_G:
        dedup_report_payload["BLOCKED"] = (
            f"final_g != {EXPECTED_FINAL_G} (the plan's directly-verified real-corpus number). "
            f"STOP: either a dedup bug or the corpus changed since the plan was written. "
            f"Re-derive every downstream number before proceeding; refusing to run the chooser "
            f"over an unverified corpus (spec Sec.6 item 6 / Sec.7)."
        )
        with open(DEDUP_REPORT_OUT, "w", encoding="utf-8") as fh:
            json.dump(dedup_report_payload, fh, indent=2, sort_keys=True)
        raise SystemExit(
            f"BLOCKED: expected final_g == {EXPECTED_FINAL_G}, got {report.final_g}. "
            f"See {DEDUP_REPORT_OUT} for details."
        )

    # --- Step 3: extract decisions from every kept file; filter to MOVE, count the rest ---
    all_decisions = []
    kind_counts = {RequestKind.MOVE: 0, RequestKind.TEAM_PREVIEW: 0, RequestKind.FORCE_SWITCH: 0}
    for p in kept_sorted:
        decisions = extract_decisions_from_log(p)
        for d in decisions:
            kind_counts[d.kind] = kind_counts.get(d.kind, 0) + 1
        all_decisions.extend(decisions)
    move_decisions = [d for d in all_decisions if d.kind == RequestKind.MOVE]
    dedup_report_payload["decision_kind_counts"] = {k.value: v for k, v in kind_counts.items()}
    dedup_report_payload["move_decision_count"] = len(move_decisions)
    with open(DEDUP_REPORT_OUT, "w", encoding="utf-8") as fh:
        json.dump(dedup_report_payload, fh, indent=2, sort_keys=True)
    print(f"dedup-report.json -> {DEDUP_REPORT_OUT}")
    print(f"decision kinds across {len(kept_sorted)} kept files: "
          f"{ {k.value: v for k, v in kind_counts.items()} }")
    print(f"{len(move_decisions)} MOVE decisions (the primary baseline sample; "
          f"team-preview/force-switch decisions carry no move-accuracy content -- spec Sec.6 "
          f"item 4 -- and are excluded from the baseline file, counts reported above)")

    # --- Step 4: real calc/oracle chain (built once, real objects -- this processes real
    # replayed battle states, not fakes) ---
    book = load_spread_book(load_format_config(FORMAT_ID).meta_path("default_spreads"))
    calc = CalcClient()
    speed_oracle = SpeedOracle(stats_backend=calc.backend)
    dex = SpeciesDex(calc.backend)

    # KNOWN, PRE-EXISTING gap in heuristic_choose_for_request's trace population (discovered
    # while wiring this driver -- NOT introduced here, and battle/decision.py is deliberately
    # left untouched this task): _maybe_tera (decision.py) can overlay a Tera flag onto the
    # already-chosen best_ja AFTER trace.candidates was built from the pre-Tera `items`, so
    # trace.chosen_candidate_id (built from the POST-Tera best_ja) can carry a " tera" suffix
    # that no entry in trace.candidates has (_label_ja appends " tera" per-slot iff
    # sa.terastallize; _maybe_tera only ever flips terastallize flags on the pre-Tera best_ja's
    # OWN slot0/slot1 -- it never changes which move/target was chosen). Stripping " tera" from
    # both sides recovers the correct pre-Tera candidate 1:1. The recorded score is therefore
    # the pre-Tera-overlay aggregate_score (the Tera-inclusive value is a local variable inside
    # _maybe_tera, not exposed by the public trace API) -- a documented approximation, applied
    # identically here and in any later Task 10 run using this same recipe, so it does not bias
    # a pre-vs-post-refactor diff.
    _tera_fallback_count = 0
    from showdown_bot.battle.candidate_identity import (
        ChosenCandidateResolutionError,
        resolve_chosen_candidate,
    )

    def _chooser(decision, *, accuracy_mode: bool):
        nonlocal _tera_fallback_count
        os.environ["SHOWDOWN_ACCURACY_MODE"] = "1" if accuracy_mode else "0"
        trace = DecisionTrace()
        chosen = heuristic_choose_for_request(
            decision.request, state=decision.state, book=book, our_side=decision.side,
            calc=calc, oracle=DamageOracle(calc), speed_oracle=speed_oracle, dex=dex, trace=trace,
        )
        try:
            resolved = resolve_chosen_candidate(trace)
        except ChosenCandidateResolutionError as exc:
            raise RuntimeError(str(exc)) from exc
        if trace.chosen_candidate_key is None and trace.chosen_candidate_id != resolved.candidate_id:
            _tera_fallback_count += 1
        return chosen, resolved.aggregate_score

    # --- Step 5 (dry run): 50-decision timed sample for a runtime ESTIMATE only, discarded.
    # Gate B's confirmatory run (Task 10) always uses the full deduplicated corpus (spec Sec.6
    # item 6) -- this baseline freeze follows the identical rule: freeze the full corpus, or
    # don't proceed. This dry run never writes to BASELINE_OUT. ---
    os.environ["SHOWDOWN_ACCURACY_MODE"] = "0"
    dry_sample = move_decisions[:DRY_RUN_N]
    t_dry0 = time.perf_counter()
    for d in dry_sample:
        _chooser(d, accuracy_mode=False)
    dry_elapsed = time.perf_counter() - t_dry0
    per_decision = dry_elapsed / max(1, len(dry_sample))
    est_full = per_decision * len(move_decisions)
    print(f"\ndry run: {len(dry_sample)} decisions in {dry_elapsed:.2f}s "
          f"({per_decision * 1000:.1f}ms/decision) -> "
          f"estimated FULL-corpus ({len(move_decisions)} decisions) runtime: {est_full:.1f}s "
          f"(tera-overlay trace fallback used on {_tera_fallback_count}/{len(dry_sample)} "
          f"dry-run decisions)")

    # _chooser closes over _tera_fallback_count, and the dry run above already called it on the
    # first DRY_RUN_N decisions. The real run below reprocesses those same decisions (it's the
    # full corpus, not the remainder), so without resetting here the counter printed after Step 6
    # would double-count any dry-run hits on top of the real run's own -- reset so the final
    # printed count reflects only the real full-corpus run.
    _tera_fallback_count = 0

    # --- Step 6: provenance, then the real, full-corpus freeze ---
    try:
        source_commit = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=str(REPO_ROOT), text=True
        ).strip()
    except Exception as exc:  # noqa: BLE001 - provenance is load-bearing; fail loud, don't guess
        raise SystemExit(f"could not determine source_commit via git rev-parse HEAD: {exc}")

    _behavior_env = behavior_env()  # captured with SHOWDOWN_ACCURACY_MODE=0 already set above
    priors_hash = _file_content_hash(load_format_config(FORMAT_ID).meta_path("protect_priors"))
    spreads_hash = _file_content_hash(load_format_config(FORMAT_ID).meta_path("default_spreads"))
    movedata_hash = _file_content_hash(movedata_path())
    provenance = config_provenance_for_format(FORMAT_ID)
    manifest = build_config_manifest(
        agent="heuristic", format_id=FORMAT_ID,
        priors_hash=priors_hash, spreads_hash=spreads_hash, env=_behavior_env,
        movedata_hash=movedata_hash,
        format_config_hash=provenance["format_config_hash"],
        calc_pin_hash=provenance["calc_pin_hash"],
    )
    config_hash = make_config_hash(manifest)

    # No requirements*.txt / poetry.lock / uv.lock in this repo (checked before writing this
    # script) -- pyproject.toml IS the pinned-deps source of truth, so hash it directly.
    lock_file = SHOWDOWN_BOT_ROOT / "pyproject.toml"
    dependency_lock_hash = hashlib.sha256(lock_file.read_bytes()).hexdigest()

    print(f"\nfreezing FULL corpus: {len(move_decisions)} MOVE decisions, accuracy_mode=off")
    print(f"  source_commit={source_commit}")
    print(f"  config_hash={config_hash}")
    print(f"  python_version={sys.version!r}")
    print(f"  dependency_lock_hash={dependency_lock_hash}")

    t0 = time.perf_counter()
    rows = freeze_baseline(
        move_decisions, out_path=BASELINE_OUT, chooser=_chooser,
        source_commit=source_commit, config_hash=config_hash,
        python_version=sys.version, dependency_lock_hash=dependency_lock_hash,
    )
    real_elapsed = time.perf_counter() - t0
    print(f"\nwrote {len(rows)} rows -> {BASELINE_OUT} in {real_elapsed:.1f}s")
    print(f"  tera-overlay trace fallback used on {_tera_fallback_count}/{len(rows)} rows "
          f"(see _chooser's docstring-comment above for why this is a known, pre-existing gap "
          f"in heuristic_choose_for_request's trace population, not a driver-script bug)")

    try:
        calc.close()
    except Exception:  # noqa: BLE001 - best-effort cleanup, never fail the run over it
        pass

    print("\nDONE.")


if __name__ == "__main__":
    main()
