"""Task 7 driver (accuracy-offline-gate plan): post-refactor baseline diff.

Replays the IDENTICAL deduplicated corpus Task 4 froze
(``data/eval/accuracy-gate/pre-refactor-baseline.jsonl``) through the NOW-refactored
``heuristic_choose_for_request`` -- Task 5/6's ``LineEvaluation``/``_evaluate_line_details``
refactor -- with ``SHOWDOWN_ACCURACY_MODE`` explicitly off, and diffs the replay against the
frozen baseline via ``accuracy_baseline_diff.diff_against_baseline``. This is the true
refactor-regression check (spec Sec.4's "runs twice, for two different purposes" requirement):
unset-vs-explicit-off alone cannot catch a bug in a wrapper both paths route through after the
refactor -- only replaying the real corpus through the real post-refactor code and diffing
against a snapshot taken before the refactor can.

This driver deliberately mirrors ``run_accuracy_baseline_freeze.py`` (Task 4) line-for-line for
every piece that determines WHICH corpus gets replayed and HOW a decision is turned into a
(chosen_action, score) pair: the same glob dirs, the same manifest files, the same
``keep_priority``, the same ``deduplicate_battle_logs``/``extract_decisions_from_log`` calls from
``room_raw_replay.py``, and the same ``_chooser`` closure (including its tera-overlay
candidate-id-stripping fallback -- a documented, pre-existing gap in
``heuristic_choose_for_request``'s trace population that Task 4's driver worked around; decision.py
was not touched to fix it, so the same workaround is still needed here). Only the "freeze vs.
diff" tail end differs. If the corpus-extraction constants below ever drift from
``run_accuracy_baseline_freeze.py``'s, the two scripts are no longer comparing the same corpus and
this diff is meaningless -- keep them in sync by inspection since the constants are simple literal
path lists, not shared logic that can be imported without also importing the freeze script's
hard "never re-run" guard.

Usage (from the showdown_bot/ directory of this worktree):

    PYTHONPATH="$(pwd)/src" python scripts/run_accuracy_baseline_diff.py

(PYTHONPATH must point at THIS worktree's src/ -- the machine has an editable pip install of
showdown-bot pointing at the main repo checkout, not this worktree; without the override,
imports silently resolve to the wrong package.)
"""

from __future__ import annotations

import glob
import json
import os
import subprocess
import sys
import time
from pathlib import Path

# Real calc backend, persistent Node process -- matches Task 4's driver (avoids a fresh spawn per
# decision across the ~944 real MOVE decisions this script replays). SHOWDOWN_CALC_BACKEND is
# NON_BEHAVIORAL (eval/config_env.py) -- transport only, never affects config_hash or the chosen
# move.
os.environ.setdefault("SHOWDOWN_CALC_BACKEND", "persistent")

SCRIPT_DIR = Path(__file__).resolve().parent
SHOWDOWN_BOT_ROOT = SCRIPT_DIR.parent
REPO_ROOT = SHOWDOWN_BOT_ROOT.parent
sys.path.insert(0, str(SHOWDOWN_BOT_ROOT / "src"))  # shadow the editable install (main-repo gotcha)

DATA_EVAL = REPO_ROOT / "data" / "eval"
OUT_DIR = DATA_EVAL / "accuracy-gate"
BASELINE_IN = OUT_DIR / "pre-refactor-baseline.jsonl"  # read-only, frozen by Task 4 -- never written here
DIFF_REPORT_OUT = OUT_DIR / "post-refactor-diff-report.json"

FORMAT_ID = "gen9vgc2025regi"
EXPECTED_FINAL_G = 85  # same corpus-size invariant Task 4's driver checked


def main() -> None:
    from showdown_bot.battle.decision import heuristic_choose_for_request
    from showdown_bot.battle.decision_trace import DecisionTrace
    from showdown_bot.battle.opponent import SpeciesDex
    from showdown_bot.battle.oracle import DamageOracle
    from showdown_bot.engine.belief.hypotheses import load_spread_book
    from showdown_bot.engine.calc.client import CalcClient
    from showdown_bot.engine.format_config import load_format_config
    from showdown_bot.engine.speed import SpeedOracle
    from showdown_bot.eval.accuracy_baseline import canonical_float
    from showdown_bot.eval.accuracy_baseline_diff import diff_against_baseline
    from showdown_bot.eval.room_raw_replay import (
        RequestKind,
        deduplicate_battle_logs,
        extract_decisions_from_log,
    )

    print(f"showdown_bot resolved from: {SHOWDOWN_BOT_ROOT}")

    if not BASELINE_IN.exists():
        raise SystemExit(
            f"BLOCKED: {BASELINE_IN} does not exist. This driver diffs against Task 4's frozen "
            f"baseline artifact -- it must already exist and must NEVER be generated by this "
            f"script (this script only reads it)."
        )

    baseline_rows = []
    with open(BASELINE_IN, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                baseline_rows.append(json.loads(line))
    print(f"loaded {len(baseline_rows)} rows from frozen baseline: {BASELINE_IN}")

    # --- Step 1: glob every .log.gz under the 4 canonical corpus directories (identical to
    # run_accuracy_baseline_freeze.py) ---
    glob_dirs = [
        DATA_EVAL / "t4" / "rerun" / "room_raw",
        DATA_EVAL / "t4" / "room_raw_divergent",
        DATA_EVAL / "t6" / "room_raw",
        DATA_EVAL / "kaggle-validation" / "room_raw",
    ]
    log_files: list[Path] = []
    for d in glob_dirs:
        log_files += [Path(p) for p in glob.glob(str(d / "**" / "*.log.gz"), recursive=True)]
    log_files = sorted(set(log_files), key=str)
    print(f"found {len(log_files)} .log.gz files under the 4 canonical corpus directories")

    # --- Step 2: global battle-level dedup (identical to run_accuracy_baseline_freeze.py) ---
    manifest_files = [
        DATA_EVAL / "t4" / "rerun" / "t4rerun-run1.jsonl",
        DATA_EVAL / "t4" / "rerun" / "t4rerun-run2.jsonl",
        DATA_EVAL / "t4" / "rerun" / "t4rerun-prefix.jsonl",
        DATA_EVAL / "t6" / "t6-run1.jsonl",
        DATA_EVAL / "t6" / "t6-run2.jsonl",
        DATA_EVAL / "kaggle-validation" / "results.jsonl",
    ]
    report = deduplicate_battle_logs(
        log_files=log_files, manifest_files=manifest_files,
        keep_priority=["run1", "run2", "prefix", "kaggle-validation"],
    )
    print(f"dedup: files_found={report.files_found} kept={len(report.kept)} "
          f"excluded={len(report.excluded)} final_g={report.final_g}")

    if report.final_g != EXPECTED_FINAL_G:
        raise SystemExit(
            f"BLOCKED: expected final_g == {EXPECTED_FINAL_G} (Task 4's frozen corpus size), "
            f"got {report.final_g}. The corpus this driver would replay does not match the "
            f"corpus Task 4 froze the baseline from -- refusing to produce a diff that would "
            f"compare two different corpora."
        )

    # --- Step 3: extract decisions from every kept file; filter to MOVE (identical to Task 4) ---
    kept_sorted = sorted(report.kept, key=str)
    all_decisions = []
    for p in kept_sorted:
        all_decisions.extend(extract_decisions_from_log(p))
    move_decisions = [d for d in all_decisions if d.kind == RequestKind.MOVE]
    print(f"{len(move_decisions)} MOVE decisions extracted from {len(kept_sorted)} kept files")

    if len(move_decisions) != len(baseline_rows):
        print(
            f"WARNING: replay corpus has {len(move_decisions)} MOVE decisions but the frozen "
            f"baseline has {len(baseline_rows)} rows. Proceeding with the diff anyway -- "
            f"missing_from_replay/extra_in_replay below will surface the exact mismatch by "
            f"request_hash rather than just a count."
        )

    # --- Step 4: real calc/oracle chain (identical to run_accuracy_baseline_freeze.py) ---
    book = load_spread_book(load_format_config(FORMAT_ID).meta_path("default_spreads"))
    calc = CalcClient()
    speed_oracle = SpeedOracle(stats_backend=calc.backend)
    dex = SpeciesDex(calc.backend)

    # Same documented, pre-existing tera-overlay trace gap Task 4's driver worked around (see
    # that script's _chooser docstring-comment for the full explanation) -- decision.py's
    # _maybe_tera still overlays a Tera flag onto the already-chosen best_ja AFTER
    # trace.candidates was built, post-refactor as pre-refactor (Tasks 5/6 only touched the
    # trace-population block inside `if trace is not None:`, not _maybe_tera or the
    # chosen-action/aggregate_score selection logic itself -- verified by reading the diff before
    # writing this driver). Stripping " tera" from both sides recovers the correct pre-Tera
    # candidate 1:1, identically to Task 4.
    _tera_fallback_count = 0

    def _strip_tera(label: str) -> str:
        return label.replace(" tera", "")

    def _chooser(decision, *, accuracy_mode: bool):
        nonlocal _tera_fallback_count
        os.environ["SHOWDOWN_ACCURACY_MODE"] = "1" if accuracy_mode else "0"
        trace = DecisionTrace()
        chosen = heuristic_choose_for_request(
            decision.request, state=decision.state, book=book, our_side=decision.side,
            calc=calc, oracle=DamageOracle(calc), speed_oracle=speed_oracle, dex=dex, trace=trace,
        )
        exact = [c for c in trace.candidates if c.candidate_id == trace.chosen_candidate_id]
        if exact:
            return chosen, exact[0].aggregate_score
        stripped_target = _strip_tera(trace.chosen_candidate_id or "")
        fallback = [c for c in trace.candidates if _strip_tera(c.candidate_id) == stripped_target]
        if len(fallback) == 1:
            _tera_fallback_count += 1
            return chosen, fallback[0].aggregate_score
        raise RuntimeError(
            f"could not resolve chosen_candidate_id={trace.chosen_candidate_id!r} against "
            f"trace.candidates={[c.candidate_id for c in trace.candidates]!r} "
            f"(exact=0, tera-stripped matches={len(fallback)}) -- refusing to guess a score"
        )

    # --- Step 5: replay the FULL corpus, accuracy off (unset-vs-"0" equivalence is covered by
    # its own dedicated test; using explicit "0" here for the same provenance-clarity reason
    # Task 4's driver did) ---
    print(f"\nreplaying FULL corpus: {len(move_decisions)} MOVE decisions, accuracy_mode=off "
          f"(post-refactor code)")
    t0 = time.perf_counter()
    replay_rows = []
    for d in move_decisions:
        chosen_action, score = _chooser(d, accuracy_mode=False)
        replay_rows.append({
            "request_hash": d.request_hash,
            "log_prefix_hash": d.log_prefix_hash,
            "side": d.side,
            "turn": d.turn,
            "chosen_action": chosen_action,
            "score": canonical_float(score),
        })
    elapsed = time.perf_counter() - t0
    print(f"replayed {len(replay_rows)} decisions in {elapsed:.1f}s "
          f"(tera-overlay trace fallback used on {_tera_fallback_count}/{len(replay_rows)} rows)")

    try:
        calc.close()
    except Exception:  # noqa: BLE001 - best-effort cleanup, never fail the run over it
        pass

    # --- Step 6: diff against the frozen baseline ---
    result = diff_against_baseline(baseline_rows, replay_rows)

    try:
        post_refactor_commit = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=str(REPO_ROOT), text=True
        ).strip()
    except Exception:  # noqa: BLE001 - provenance is best-effort for the report; never block on it
        post_refactor_commit = None

    baseline_source_commit = baseline_rows[0].get("source_commit") if baseline_rows else None

    report_payload = {
        "baseline_path": str(BASELINE_IN.resolve().relative_to(REPO_ROOT).as_posix()),
        "baseline_row_count": len(baseline_rows),
        "baseline_source_commit": baseline_source_commit,
        "replay_row_count": len(replay_rows),
        "post_refactor_commit": post_refactor_commit,
        "replay_final_g": report.final_g,
        "matched": result.matched,
        "regressions_count": len(result.regressions),
        "regressions": [
            {
                "request_hash": r.request_hash,
                "baseline_action": r.baseline_action,
                "replay_action": r.replay_action,
                "baseline_score": r.baseline_score,
                "replay_score": r.replay_score,
            }
            for r in result.regressions
        ],
        "missing_from_replay": result.missing_from_replay,
        "extra_in_replay": result.extra_in_replay,
        "tera_fallback_count": _tera_fallback_count,
        "elapsed_seconds": round(elapsed, 1),
    }
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(DIFF_REPORT_OUT, "w", encoding="utf-8") as fh:
        json.dump(report_payload, fh, indent=2, sort_keys=True)

    print(f"\nmatched={result.matched} regressions={len(result.regressions)} "
          f"missing_from_replay={len(result.missing_from_replay)} "
          f"extra_in_replay={len(result.extra_in_replay)}")
    print(f"report written -> {DIFF_REPORT_OUT}")

    if result.regressions or result.missing_from_replay or result.extra_in_replay:
        print("\nBLOCKED: the post-refactor replay diverges from the frozen pre-refactor "
              "baseline. See the report above/on disk for exact request_hash-level detail. "
              "Do NOT paper over this -- it means Task 5 or Task 6 changed real off-path "
              "behavior.")
        raise SystemExit(1)

    print("\nDONE: post-refactor off-path replay is byte-identical to the frozen pre-refactor "
          "baseline over the full deduplicated corpus.")


if __name__ == "__main__":
    main()
